/* eslint-disable @typescript-eslint/naming-convention */
import { expect } from 'chai';

import { evaluateId, getInvoices } from './updater';

const applicationFee = 1;

const paymentPlan = 2;

const material = 3;

const tuitionFee = 4;

describe('Updater', function () {
    it('should evaluateId for Application Fee', function () {
        const productId = evaluateId({
            feeName: 'Application Fee',
            applicationFee,
            paymentPlan,
            material,
            tuitionFee,
        });

        expect(productId).to.be.eql(applicationFee);
    });

    it('should evaluateId for Enrolment Fee', function () {
        const productId = evaluateId({
            feeName: 'Enrolment Fee',
            applicationFee,
            paymentPlan,
            material,
            tuitionFee,
        });

        expect(productId).to.be.eql(applicationFee);
    });

    it('should evaluateId for Tuition fee', function () {
        const productId = evaluateId({
            feeName: 'CHC30121 Tuition fee',
            applicationFee,
            paymentPlan,
            material,
            tuitionFee,
        });

        expect(productId).to.be.eql(tuitionFee);
    });

    it('should get invoices for Tuition fee for Advit', function () {
        const invoices = getInvoices({
            result: {
                attachmentId: 8384,
                courses: [
                    {
                        name: 'Advanced Diploma of Information Technology',
                        code: ' ICT60220',
                        schedules: [
                            {
                                dueDate: '26/11/2021',
                                feeName: 'Enrolment Fee',
                                amount: 250,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '26/11/2021',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '26/11/2021',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '11/07/2022',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '11/07/2022',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '10/10/2022',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '10/10/2022',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '09/01/2023',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '09/01/2023',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '10/04/2023',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '10/04/2023',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '10/07/2023',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '10/07/2023',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '09/10/2023',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '09/10/2023',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '08/01/2024',
                                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
                                amount: 2300,
                                courseCode: ' ICT60220',
                            },
                            {
                                dueDate: '08/01/2024',
                                feeName: 'Material Fee',
                                amount: 100,
                                courseCode: ' ICT60220',
                            },
                        ],
                    },
                ],
            },
            applicationFee: 7034,
            paymentPlan: 7035,
            material: 7036,
            tuitionFee: 7037,
            contactid: 7112,
            accountid: 6357,
        });

        console.info('invoices:', JSON.stringify(invoices));

        expect(invoices).to.be.eql([
            {
                subject: 'Nov 2021 - Enrolment Fee',
                contactid: 7112,
                invoicedate: '2021-11-26',
                subtotal: 250,
                total: 250,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV112021',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 250,
                balance: 250,
                productId: 7034,
                feeName: 'Enrolment Fee',
            },
            {
                subject: 'Nov 2021 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2021-11-26',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV112021',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Nov 2021 - Material Fee',
                contactid: 7112,
                invoicedate: '2021-11-26',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV112021',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Jul 2022 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2022-07-11',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV072022',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Jul 2022 - Material Fee',
                contactid: 7112,
                invoicedate: '2022-07-11',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV072022',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Oct 2022 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2022-10-10',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV102022',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Oct 2022 - Material Fee',
                contactid: 7112,
                invoicedate: '2022-10-10',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV102022',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Jan 2023 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2023-01-09',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV012023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Jan 2023 - Material Fee',
                contactid: 7112,
                invoicedate: '2023-01-09',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV012023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Apr 2023 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2023-04-10',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV042023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Apr 2023 - Material Fee',
                contactid: 7112,
                invoicedate: '2023-04-10',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV042023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Jul 2023 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2023-07-10',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV072023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Jul 2023 - Material Fee',
                contactid: 7112,
                invoicedate: '2023-07-10',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV072023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Oct 2023 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2023-10-09',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV102023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Oct 2023 - Material Fee',
                contactid: 7112,
                invoicedate: '2023-10-09',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV102023',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
            {
                subject: 'Jan 2024 - Tuition-ADVIT-TNE-NSW-Q12021',
                contactid: 7112,
                invoicedate: '2024-01-08',
                subtotal: 2300,
                total: 2300,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV012024',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 2300,
                balance: 2300,
                productId: 7037,
                feeName: 'Tuition-ADVIT-TNE-NSW-Q12021',
            },
            {
                subject: 'Jan 2024 - Material Fee',
                contactid: 7112,
                invoicedate: '2024-01-08',
                subtotal: 100,
                total: 100,
                taxtype: 'group',
                accountid: 6357,
                invoicestatus: 'Sent',
                invoice_no: 'INV012024',
                currency_id: 1,
                conversion_rate: 1,
                pre_tax_total: 100,
                balance: 100,
                productId: 7036,
                feeName: 'Material Fee',
            },
        ]);
    });

    it('should evaluateId for Material fee', function () {
        const productId = evaluateId({
            feeName: 'CHC30121 Material fee',
            applicationFee,
            paymentPlan,
            material,
            tuitionFee,
        });

        expect(productId).to.be.eql(material);
    });
});
